/*
 * ZigBee Home Automation Standard Device Types
 * Based on esp_zb_ha_standard_devices_t enum type
 * Generated by generate_separate_modules.py on 2025-05-25 11:05:08
 */

#include "py/runtime.h"
#include "py/obj.h"
#include "py/objstr.h"
#include <string.h>
#include "ZCL_DEVICE.h"

// Module-level function implementations - NO INTERMEDIATE CLASS
// get_type method implementation
mp_obj_t mod_zigbee_device_get_type(mp_obj_t value_in) {
    mp_int_t value = mp_obj_get_int(value_in);
    
    // Return type information based on value
    switch (value) {
        case 0x0000:
            return mp_obj_new_str("ESP_ZB_HA_ON_OFF_SWITCH_DEVICE_ID", strlen("ESP_ZB_HA_ON_OFF_SWITCH_DEVICE_ID"));
        case 0x0001:
            return mp_obj_new_str("ESP_ZB_HA_LEVEL_CONTROL_SWITCH_DEVICE_ID", strlen("ESP_ZB_HA_LEVEL_CONTROL_SWITCH_DEVICE_ID"));
        case 0x0002:
            return mp_obj_new_str("ESP_ZB_HA_ON_OFF_OUTPUT_DEVICE_ID", strlen("ESP_ZB_HA_ON_OFF_OUTPUT_DEVICE_ID"));
        case 0x0003:
            return mp_obj_new_str("ESP_ZB_HA_LEVEL_CONTROLLABLE_OUTPUT_DEVICE_ID", strlen("ESP_ZB_HA_LEVEL_CONTROLLABLE_OUTPUT_DEVICE_ID"));
        case 0x0004:
            return mp_obj_new_str("ESP_ZB_HA_SCENE_SELECTOR_DEVICE_ID", strlen("ESP_ZB_HA_SCENE_SELECTOR_DEVICE_ID"));
        case 0x0005:
            return mp_obj_new_str("ESP_ZB_HA_CONFIGURATION_TOOL_DEVICE_ID", strlen("ESP_ZB_HA_CONFIGURATION_TOOL_DEVICE_ID"));
        case 0x0006:
            return mp_obj_new_str("ESP_ZB_HA_REMOTE_CONTROL_DEVICE_ID", strlen("ESP_ZB_HA_REMOTE_CONTROL_DEVICE_ID"));
        case 0x0007:
            return mp_obj_new_str("ESP_ZB_HA_COMBINED_INTERFACE_DEVICE_ID", strlen("ESP_ZB_HA_COMBINED_INTERFACE_DEVICE_ID"));
        case 0x0008:
            return mp_obj_new_str("ESP_ZB_HA_RANGE_EXTENDER_DEVICE_ID", strlen("ESP_ZB_HA_RANGE_EXTENDER_DEVICE_ID"));
        case 0x0009:
            return mp_obj_new_str("ESP_ZB_HA_MAINS_POWER_OUTLET_DEVICE_ID", strlen("ESP_ZB_HA_MAINS_POWER_OUTLET_DEVICE_ID"));
        case 0x000A:
            return mp_obj_new_str("ESP_ZB_HA_DOOR_LOCK_DEVICE_ID", strlen("ESP_ZB_HA_DOOR_LOCK_DEVICE_ID"));
        case 0x000B:
            return mp_obj_new_str("ESP_ZB_HA_DOOR_LOCK_CONTROLLER_DEVICE_ID", strlen("ESP_ZB_HA_DOOR_LOCK_CONTROLLER_DEVICE_ID"));
        case 0x000C:
            return mp_obj_new_str("ESP_ZB_HA_SIMPLE_SENSOR_DEVICE_ID", strlen("ESP_ZB_HA_SIMPLE_SENSOR_DEVICE_ID"));
        case 0x000D:
            return mp_obj_new_str("ESP_ZB_HA_CONSUMPTION_AWARENESS_DEVICE_ID", strlen("ESP_ZB_HA_CONSUMPTION_AWARENESS_DEVICE_ID"));
        case 0x0050:
            return mp_obj_new_str("ESP_ZB_HA_HOME_GATEWAY_DEVICE_ID", strlen("ESP_ZB_HA_HOME_GATEWAY_DEVICE_ID"));
        case 0x0051:
            return mp_obj_new_str("ESP_ZB_HA_SMART_PLUG_DEVICE_ID", strlen("ESP_ZB_HA_SMART_PLUG_DEVICE_ID"));
        case 0x0052:
            return mp_obj_new_str("ESP_ZB_HA_WHITE_GOODS_DEVICE_ID", strlen("ESP_ZB_HA_WHITE_GOODS_DEVICE_ID"));
        case 0x0053:
            return mp_obj_new_str("ESP_ZB_HA_METER_INTERFACE_DEVICE_ID", strlen("ESP_ZB_HA_METER_INTERFACE_DEVICE_ID"));
        case 0x0100:
            return mp_obj_new_str("ESP_ZB_HA_ON_OFF_LIGHT_DEVICE_ID", strlen("ESP_ZB_HA_ON_OFF_LIGHT_DEVICE_ID"));
        case 0x0101:
            return mp_obj_new_str("ESP_ZB_HA_DIMMABLE_LIGHT_DEVICE_ID", strlen("ESP_ZB_HA_DIMMABLE_LIGHT_DEVICE_ID"));
        case 0x0102:
            return mp_obj_new_str("ESP_ZB_HA_COLOR_DIMMABLE_LIGHT_DEVICE_ID", strlen("ESP_ZB_HA_COLOR_DIMMABLE_LIGHT_DEVICE_ID"));
        case 0x0104:
            return mp_obj_new_str("ESP_ZB_HA_DIMMER_SWITCH_DEVICE_ID", strlen("ESP_ZB_HA_DIMMER_SWITCH_DEVICE_ID"));
        case 0x0105:
            return mp_obj_new_str("ESP_ZB_HA_COLOR_DIMMER_SWITCH_DEVICE_ID", strlen("ESP_ZB_HA_COLOR_DIMMER_SWITCH_DEVICE_ID"));
        case 0x0106:
            return mp_obj_new_str("ESP_ZB_HA_LIGHT_SENSOR_DEVICE_ID", strlen("ESP_ZB_HA_LIGHT_SENSOR_DEVICE_ID"));
        case 0x0200:
            return mp_obj_new_str("ESP_ZB_HA_SHADE_DEVICE_ID", strlen("ESP_ZB_HA_SHADE_DEVICE_ID"));
        case 0x0201:
            return mp_obj_new_str("ESP_ZB_HA_SHADE_CONTROLLER_DEVICE_ID", strlen("ESP_ZB_HA_SHADE_CONTROLLER_DEVICE_ID"));
        case 0x0202:
            return mp_obj_new_str("ESP_ZB_HA_WINDOW_COVERING_DEVICE_ID", strlen("ESP_ZB_HA_WINDOW_COVERING_DEVICE_ID"));
        case 0x0203:
            return mp_obj_new_str("ESP_ZB_HA_WINDOW_COVERING_CONTROLLER_DEVICE_ID", strlen("ESP_ZB_HA_WINDOW_COVERING_CONTROLLER_DEVICE_ID"));
        case 0x0300:
            return mp_obj_new_str("ESP_ZB_HA_HEATING_COOLING_UNIT_DEVICE_ID", strlen("ESP_ZB_HA_HEATING_COOLING_UNIT_DEVICE_ID"));
        case 0x0301:
            return mp_obj_new_str("ESP_ZB_HA_THERMOSTAT_DEVICE_ID", strlen("ESP_ZB_HA_THERMOSTAT_DEVICE_ID"));
        case 0x0302:
            return mp_obj_new_str("ESP_ZB_HA_TEMPERATURE_SENSOR_DEVICE_ID", strlen("ESP_ZB_HA_TEMPERATURE_SENSOR_DEVICE_ID"));
        case 0x0400:
            return mp_obj_new_str("ESP_ZB_HA_IAS_CONTROL_INDICATING_EQUIPMENT_ID", strlen("ESP_ZB_HA_IAS_CONTROL_INDICATING_EQUIPMENT_ID"));
        case 0x0401:
            return mp_obj_new_str("ESP_ZB_HA_IAS_ANCILLARY_CONTROL_EQUIPMENT_ID", strlen("ESP_ZB_HA_IAS_ANCILLARY_CONTROL_EQUIPMENT_ID"));
        case 0x0402:
            return mp_obj_new_str("ESP_ZB_HA_IAS_ZONE_ID", strlen("ESP_ZB_HA_IAS_ZONE_ID"));
        case 0x0403:
            return mp_obj_new_str("ESP_ZB_HA_IAS_WARNING_DEVICE_ID", strlen("ESP_ZB_HA_IAS_WARNING_DEVICE_ID"));
        case 0xfff0:
            return mp_obj_new_str("ESP_ZB_HA_TEST_DEVICE_ID", strlen("ESP_ZB_HA_TEST_DEVICE_ID"));
        case 0xfff1:
            return mp_obj_new_str("ESP_ZB_HA_CUSTOM_TUNNEL_DEVICE_ID", strlen("ESP_ZB_HA_CUSTOM_TUNNEL_DEVICE_ID"));
        case 0xfff2:
            return mp_obj_new_str("ESP_ZB_HA_CUSTOM_ATTR_DEVICE_ID", strlen("ESP_ZB_HA_CUSTOM_ATTR_DEVICE_ID"));
        default:
            return mp_obj_new_str("UNKNOWN", 7);
    }
}
static MP_DEFINE_CONST_FUN_OBJ_1(mod_zigbee_device_get_type_obj, mod_zigbee_device_get_type);

// size method implementation  
mp_obj_t mod_zigbee_device_size(mp_obj_t value_in) {
    (void)value_in; // Mark value_in as unused for specific enum types
    
    // Return size based on enum type
    // Device/Cluster/Profile IDs are typically 16-bit (2 bytes)
    return MP_OBJ_NEW_SMALL_INT(2);
}
static MP_DEFINE_CONST_FUN_OBJ_1(mod_zigbee_device_size_obj, mod_zigbee_device_size);

// Module dictionary - functions and constants directly accessible
static const mp_rom_map_elem_t mp_module_ZCL_DEVICE_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_ZCL_DEVICE) },
    
    // Module-level functions (not class methods!)
    { MP_ROM_QSTR(MP_QSTR_get_type), MP_ROM_PTR(&mod_zigbee_device_get_type_obj) },
    { MP_ROM_QSTR(MP_QSTR_size), MP_ROM_PTR(&mod_zigbee_device_size_obj) },
    
    // Constants directly in module
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_ON_OFF_SWITCH_DEVICE_ID), MP_ROM_INT(0x0000) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_LEVEL_CONTROL_SWITCH_DEVICE_ID), MP_ROM_INT(0x0001) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_ON_OFF_OUTPUT_DEVICE_ID), MP_ROM_INT(0x0002) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_LEVEL_CONTROLLABLE_OUTPUT_DEVICE_ID), MP_ROM_INT(0x0003) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_SCENE_SELECTOR_DEVICE_ID), MP_ROM_INT(0x0004) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_CONFIGURATION_TOOL_DEVICE_ID), MP_ROM_INT(0x0005) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_REMOTE_CONTROL_DEVICE_ID), MP_ROM_INT(0x0006) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_COMBINED_INTERFACE_DEVICE_ID), MP_ROM_INT(0x0007) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_RANGE_EXTENDER_DEVICE_ID), MP_ROM_INT(0x0008) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_MAINS_POWER_OUTLET_DEVICE_ID), MP_ROM_INT(0x0009) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_DOOR_LOCK_DEVICE_ID), MP_ROM_INT(0x000A) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_DOOR_LOCK_CONTROLLER_DEVICE_ID), MP_ROM_INT(0x000B) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_SIMPLE_SENSOR_DEVICE_ID), MP_ROM_INT(0x000C) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_CONSUMPTION_AWARENESS_DEVICE_ID), MP_ROM_INT(0x000D) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_HOME_GATEWAY_DEVICE_ID), MP_ROM_INT(0x0050) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_SMART_PLUG_DEVICE_ID), MP_ROM_INT(0x0051) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_WHITE_GOODS_DEVICE_ID), MP_ROM_INT(0x0052) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_METER_INTERFACE_DEVICE_ID), MP_ROM_INT(0x0053) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_ON_OFF_LIGHT_DEVICE_ID), MP_ROM_INT(0x0100) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_DIMMABLE_LIGHT_DEVICE_ID), MP_ROM_INT(0x0101) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_COLOR_DIMMABLE_LIGHT_DEVICE_ID), MP_ROM_INT(0x0102) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_DIMMER_SWITCH_DEVICE_ID), MP_ROM_INT(0x0104) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_COLOR_DIMMER_SWITCH_DEVICE_ID), MP_ROM_INT(0x0105) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_LIGHT_SENSOR_DEVICE_ID), MP_ROM_INT(0x0106) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_SHADE_DEVICE_ID), MP_ROM_INT(0x0200) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_SHADE_CONTROLLER_DEVICE_ID), MP_ROM_INT(0x0201) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_WINDOW_COVERING_DEVICE_ID), MP_ROM_INT(0x0202) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_WINDOW_COVERING_CONTROLLER_DEVICE_ID), MP_ROM_INT(0x0203) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_HEATING_COOLING_UNIT_DEVICE_ID), MP_ROM_INT(0x0300) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_THERMOSTAT_DEVICE_ID), MP_ROM_INT(0x0301) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_TEMPERATURE_SENSOR_DEVICE_ID), MP_ROM_INT(0x0302) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_IAS_CONTROL_INDICATING_EQUIPMENT_ID), MP_ROM_INT(0x0400) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_IAS_ANCILLARY_CONTROL_EQUIPMENT_ID), MP_ROM_INT(0x0401) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_IAS_ZONE_ID), MP_ROM_INT(0x0402) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_IAS_WARNING_DEVICE_ID), MP_ROM_INT(0x0403) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_TEST_DEVICE_ID), MP_ROM_INT(0xfff0) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_CUSTOM_TUNNEL_DEVICE_ID), MP_ROM_INT(0xfff1) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_HA_CUSTOM_ATTR_DEVICE_ID), MP_ROM_INT(0xfff2) },
};
static MP_DEFINE_CONST_DICT(mp_module_ZCL_DEVICE_globals, mp_module_ZCL_DEVICE_globals_table);

// Module definition
const mp_obj_module_t mp_module_ZCL_DEVICE = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t*)&mp_module_ZCL_DEVICE_globals,
};

// Auto-register the module with MicroPython
MP_REGISTER_MODULE(MP_QSTR_ZCL_DEVICE, mp_module_ZCL_DEVICE);
