/*
 * ZigBee Cluster Library Attribute Access Rights
 * Based on esp_zb_zcl_attr_access_t enum type
 * Generated by generate_separate_modules.py on 2025-05-25 11:05:08
 */

#include "py/runtime.h"
#include "py/obj.h"
#include "py/objstr.h"
#include <string.h>
#include "ZCL_ATTR_ACCESS.h"

// Module-level function implementations - NO INTERMEDIATE CLASS
// get_type method implementation
mp_obj_t mod_zigbee_attraccess_get_type(mp_obj_t value_in) {
    mp_int_t value = mp_obj_get_int(value_in);
    
    // Return type information based on value
    switch (value) {
        case 0x01:
            return mp_obj_new_str("ESP_ZB_ZCL_ATTR_ACCESS_READ_ONLY", strlen("ESP_ZB_ZCL_ATTR_ACCESS_READ_ONLY"));
        case 0x02:
            return mp_obj_new_str("ESP_ZB_ZCL_ATTR_ACCESS_WRITE_ONLY", strlen("ESP_ZB_ZCL_ATTR_ACCESS_WRITE_ONLY"));
        case 0x03:
            return mp_obj_new_str("ESP_ZB_ZCL_ATTR_ACCESS_READ_WRITE", strlen("ESP_ZB_ZCL_ATTR_ACCESS_READ_WRITE"));
        case 0x04:
            return mp_obj_new_str("ESP_ZB_ZCL_ATTR_ACCESS_REPORTING", strlen("ESP_ZB_ZCL_ATTR_ACCESS_REPORTING"));
        case 0x08:
            return mp_obj_new_str("ESP_ZB_ZCL_ATTR_ACCESS_SINGLETON", strlen("ESP_ZB_ZCL_ATTR_ACCESS_SINGLETON"));
        case 0x10:
            return mp_obj_new_str("ESP_ZB_ZCL_ATTR_ACCESS_SCENE", strlen("ESP_ZB_ZCL_ATTR_ACCESS_SCENE"));
        case 0x20:
            return mp_obj_new_str("ESP_ZB_ZCL_ATTR_MANUF_SPEC", strlen("ESP_ZB_ZCL_ATTR_MANUF_SPEC"));
        case 0x40:
            return mp_obj_new_str("ESP_ZB_ZCL_ATTR_ACCESS_INTERNAL", strlen("ESP_ZB_ZCL_ATTR_ACCESS_INTERNAL"));
        default:
            return mp_obj_new_str("UNKNOWN", 7);
    }
}
static MP_DEFINE_CONST_FUN_OBJ_1(mod_zigbee_attraccess_get_type_obj, mod_zigbee_attraccess_get_type);

// size method implementation  
mp_obj_t mod_zigbee_attraccess_size(mp_obj_t value_in) {
    (void)value_in; // Mark value_in as unused for specific enum types
    
    // Return size based on enum type
    // Attribute access rights are typically 8-bit (1 byte)
    return MP_OBJ_NEW_SMALL_INT(1);
}
static MP_DEFINE_CONST_FUN_OBJ_1(mod_zigbee_attraccess_size_obj, mod_zigbee_attraccess_size);

// Module dictionary - functions and constants directly accessible
static const mp_rom_map_elem_t mp_module_ZCL_ATTR_ACCESS_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_ZCL_ATTR_ACCESS) },
    
    // Module-level functions (not class methods!)
    { MP_ROM_QSTR(MP_QSTR_get_type), MP_ROM_PTR(&mod_zigbee_attraccess_get_type_obj) },
    { MP_ROM_QSTR(MP_QSTR_size), MP_ROM_PTR(&mod_zigbee_attraccess_size_obj) },
    
    // Constants directly in module
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_ATTR_ACCESS_READ_ONLY), MP_ROM_INT(0x01) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_ATTR_ACCESS_WRITE_ONLY), MP_ROM_INT(0x02) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_ATTR_ACCESS_READ_WRITE), MP_ROM_INT(0x03) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_ATTR_ACCESS_REPORTING), MP_ROM_INT(0x04) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_ATTR_ACCESS_SINGLETON), MP_ROM_INT(0x08) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_ATTR_ACCESS_SCENE), MP_ROM_INT(0x10) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_ATTR_MANUF_SPEC), MP_ROM_INT(0x20) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_ATTR_ACCESS_INTERNAL), MP_ROM_INT(0x40) },
};
static MP_DEFINE_CONST_DICT(mp_module_ZCL_ATTR_ACCESS_globals, mp_module_ZCL_ATTR_ACCESS_globals_table);

// Module definition
const mp_obj_module_t mp_module_ZCL_ATTR_ACCESS = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t*)&mp_module_ZCL_ATTR_ACCESS_globals,
};

// Auto-register the module with MicroPython
MP_REGISTER_MODULE(MP_QSTR_ZCL_ATTR_ACCESS, mp_module_ZCL_ATTR_ACCESS);
