/*
 * ZigBee Core Action Callback IDs
 * Based on esp_zb_core_action_callback_id_s enum type
 * Generated by generate_separate_modules.py on 2025-05-25 11:05:08
 */

#include "py/runtime.h"
#include "py/obj.h"
#include "py/objstr.h"
#include <string.h>
#include "ZCL_ACTION_CALLBACK.h"

// Module-level function implementations - NO INTERMEDIATE CLASS
// get_type method implementation
mp_obj_t mod_zigbee_actioncallback_get_type(mp_obj_t value_in) {
    mp_int_t value = mp_obj_get_int(value_in);
    
    // Return type information based on value
    switch (value) {
        case 0x0000:
            return mp_obj_new_str("ESP_ZB_CORE_SET_ATTR_VALUE_CB_ID", strlen("ESP_ZB_CORE_SET_ATTR_VALUE_CB_ID"));
        case 0x0001:
            return mp_obj_new_str("ESP_ZB_CORE_SCENES_STORE_SCENE_CB_ID", strlen("ESP_ZB_CORE_SCENES_STORE_SCENE_CB_ID"));
        case 0x0002:
            return mp_obj_new_str("ESP_ZB_CORE_SCENES_RECALL_SCENE_CB_ID", strlen("ESP_ZB_CORE_SCENES_RECALL_SCENE_CB_ID"));
        case 0x0003:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ZONE_ENROLL_RESPONSE_VALUE_CB_ID", strlen("ESP_ZB_CORE_IAS_ZONE_ENROLL_RESPONSE_VALUE_CB_ID"));
        case 0x0004:
            return mp_obj_new_str("ESP_ZB_CORE_OTA_UPGRADE_VALUE_CB_ID", strlen("ESP_ZB_CORE_OTA_UPGRADE_VALUE_CB_ID"));
        case 0x0005:
            return mp_obj_new_str("ESP_ZB_CORE_OTA_UPGRADE_SRV_STATUS_CB_ID", strlen("ESP_ZB_CORE_OTA_UPGRADE_SRV_STATUS_CB_ID"));
        case 0x0006:
            return mp_obj_new_str("ESP_ZB_CORE_OTA_UPGRADE_SRV_QUERY_IMAGE_CB_ID", strlen("ESP_ZB_CORE_OTA_UPGRADE_SRV_QUERY_IMAGE_CB_ID"));
        case 0x0007:
            return mp_obj_new_str("ESP_ZB_CORE_THERMOSTAT_VALUE_CB_ID", strlen("ESP_ZB_CORE_THERMOSTAT_VALUE_CB_ID"));
        case 0x0008:
            return mp_obj_new_str("ESP_ZB_CORE_METERING_GET_PROFILE_CB_ID", strlen("ESP_ZB_CORE_METERING_GET_PROFILE_CB_ID"));
        case 0x0009:
            return mp_obj_new_str("ESP_ZB_CORE_METERING_GET_PROFILE_RESP_CB_ID", strlen("ESP_ZB_CORE_METERING_GET_PROFILE_RESP_CB_ID"));
        case 0x000a:
            return mp_obj_new_str("ESP_ZB_CORE_METERING_REQ_FAST_POLL_MODE_CB_ID", strlen("ESP_ZB_CORE_METERING_REQ_FAST_POLL_MODE_CB_ID"));
        case 0x000b:
            return mp_obj_new_str("ESP_ZB_CORE_METERING_REQ_FAST_POLL_MODE_RESP_CB_ID", strlen("ESP_ZB_CORE_METERING_REQ_FAST_POLL_MODE_RESP_CB_ID"));
        case 0x000c:
            return mp_obj_new_str("ESP_ZB_CORE_METERING_GET_SNAPSHOT_CB_ID", strlen("ESP_ZB_CORE_METERING_GET_SNAPSHOT_CB_ID"));
        case 0x000d:
            return mp_obj_new_str("ESP_ZB_CORE_METERING_PUBLISH_SNAPSHOT_CB_ID", strlen("ESP_ZB_CORE_METERING_PUBLISH_SNAPSHOT_CB_ID"));
        case 0x000e:
            return mp_obj_new_str("ESP_ZB_CORE_METERING_GET_SAMPLED_DATA_CB_ID", strlen("ESP_ZB_CORE_METERING_GET_SAMPLED_DATA_CB_ID"));
        case 0x000f:
            return mp_obj_new_str("ESP_ZB_CORE_METERING_GET_SAMPLED_DATA_RESP_CB_ID", strlen("ESP_ZB_CORE_METERING_GET_SAMPLED_DATA_RESP_CB_ID"));
        case 0x0010:
            return mp_obj_new_str("ESP_ZB_CORE_DOOR_LOCK_LOCK_DOOR_CB_ID", strlen("ESP_ZB_CORE_DOOR_LOCK_LOCK_DOOR_CB_ID"));
        case 0x0011:
            return mp_obj_new_str("ESP_ZB_CORE_DOOR_LOCK_LOCK_DOOR_RESP_CB_ID", strlen("ESP_ZB_CORE_DOOR_LOCK_LOCK_DOOR_RESP_CB_ID"));
        case 0x0012:
            return mp_obj_new_str("ESP_ZB_CORE_IDENTIFY_EFFECT_CB_ID", strlen("ESP_ZB_CORE_IDENTIFY_EFFECT_CB_ID"));
        case 0x0013:
            return mp_obj_new_str("ESP_ZB_CORE_BASIC_RESET_TO_FACTORY_RESET_CB_ID", strlen("ESP_ZB_CORE_BASIC_RESET_TO_FACTORY_RESET_CB_ID"));
        case 0x0014:
            return mp_obj_new_str("ESP_ZB_CORE_PRICE_GET_CURRENT_PRICE_CB_ID", strlen("ESP_ZB_CORE_PRICE_GET_CURRENT_PRICE_CB_ID"));
        case 0x0015:
            return mp_obj_new_str("ESP_ZB_CORE_PRICE_GET_SCHEDULED_PRICES_CB_ID", strlen("ESP_ZB_CORE_PRICE_GET_SCHEDULED_PRICES_CB_ID"));
        case 0x0016:
            return mp_obj_new_str("ESP_ZB_CORE_PRICE_GET_TIER_LABELS_CB_ID", strlen("ESP_ZB_CORE_PRICE_GET_TIER_LABELS_CB_ID"));
        case 0x0017:
            return mp_obj_new_str("ESP_ZB_CORE_PRICE_PUBLISH_PRICE_CB_ID", strlen("ESP_ZB_CORE_PRICE_PUBLISH_PRICE_CB_ID"));
        case 0x0018:
            return mp_obj_new_str("ESP_ZB_CORE_PRICE_PUBLISH_TIER_LABELS_CB_ID", strlen("ESP_ZB_CORE_PRICE_PUBLISH_TIER_LABELS_CB_ID"));
        case 0x0019:
            return mp_obj_new_str("ESP_ZB_CORE_PRICE_PRICE_ACK_CB_ID", strlen("ESP_ZB_CORE_PRICE_PRICE_ACK_CB_ID"));
        case 0x001a:
            return mp_obj_new_str("ESP_ZB_CORE_COMM_RESTART_DEVICE_CB_ID", strlen("ESP_ZB_CORE_COMM_RESTART_DEVICE_CB_ID"));
        case 0x001b:
            return mp_obj_new_str("ESP_ZB_CORE_COMM_OPERATE_STARTUP_PARAMS_CB_ID", strlen("ESP_ZB_CORE_COMM_OPERATE_STARTUP_PARAMS_CB_ID"));
        case 0x001c:
            return mp_obj_new_str("ESP_ZB_CORE_COMM_COMMAND_RESP_CB_ID", strlen("ESP_ZB_CORE_COMM_COMMAND_RESP_CB_ID"));
        case 0x001d:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_WD_START_WARNING_CB_ID", strlen("ESP_ZB_CORE_IAS_WD_START_WARNING_CB_ID"));
        case 0x001e:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_WD_SQUAWK_CB_ID", strlen("ESP_ZB_CORE_IAS_WD_SQUAWK_CB_ID"));
        case 0x001f:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_ARM_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_ARM_CB_ID"));
        case 0x0020:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_BYPASS_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_BYPASS_CB_ID"));
        case 0x0021:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_EMERGENCY_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_EMERGENCY_CB_ID"));
        case 0x0022:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_FIRE_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_FIRE_CB_ID"));
        case 0x0023:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_PANIC_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_PANIC_CB_ID"));
        case 0x0024:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_GET_PANEL_STATUS_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_GET_PANEL_STATUS_CB_ID"));
        case 0x0025:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_GET_BYPASSED_ZONE_LIST_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_GET_BYPASSED_ZONE_LIST_CB_ID"));
        case 0x0026:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_GET_ZONE_STATUS_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_GET_ZONE_STATUS_CB_ID"));
        case 0x0027:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_ARM_RESP_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_ARM_RESP_CB_ID"));
        case 0x0028:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_GET_ZONE_ID_MAP_RESP_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_GET_ZONE_ID_MAP_RESP_CB_ID"));
        case 0x0029:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_GET_ZONE_INFO_RESP_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_GET_ZONE_INFO_RESP_CB_ID"));
        case 0x002a:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_ZONE_STATUS_CHANGED_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_ZONE_STATUS_CHANGED_CB_ID"));
        case 0x002b:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_PANEL_STATUS_CHANGED_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_PANEL_STATUS_CHANGED_CB_ID"));
        case 0x002c:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_GET_PANEL_STATUS_RESP_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_GET_PANEL_STATUS_RESP_CB_ID"));
        case 0x002d:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_SET_BYPASSED_ZONE_LIST_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_SET_BYPASSED_ZONE_LIST_CB_ID"));
        case 0x002e:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_BYPASS_RESP_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_BYPASS_RESP_CB_ID"));
        case 0x002f:
            return mp_obj_new_str("ESP_ZB_CORE_IAS_ACE_GET_ZONE_STATUS_RESP_CB_ID", strlen("ESP_ZB_CORE_IAS_ACE_GET_ZONE_STATUS_RESP_CB_ID"));
        case 0x0030:
            return mp_obj_new_str("ESP_ZB_CORE_WINDOW_COVERING_MOVEMENT_CB_ID", strlen("ESP_ZB_CORE_WINDOW_COVERING_MOVEMENT_CB_ID"));
        case 0x0031:
            return mp_obj_new_str("ESP_ZB_CORE_OTA_UPGRADE_QUERY_IMAGE_RESP_CB_ID", strlen("ESP_ZB_CORE_OTA_UPGRADE_QUERY_IMAGE_RESP_CB_ID"));
        case 0x0032:
            return mp_obj_new_str("ESP_ZB_CORE_THERMOSTAT_WEEKLY_SCHEDULE_SET_CB_ID", strlen("ESP_ZB_CORE_THERMOSTAT_WEEKLY_SCHEDULE_SET_CB_ID"));
        case 0x0040:
            return mp_obj_new_str("ESP_ZB_CORE_DRLC_LOAD_CONTORL_EVENT_CB_ID", strlen("ESP_ZB_CORE_DRLC_LOAD_CONTORL_EVENT_CB_ID"));
        case 0x0041:
            return mp_obj_new_str("ESP_ZB_CORE_DRLC_CANCEL_LOAD_CONTROL_EVENT_CB_ID", strlen("ESP_ZB_CORE_DRLC_CANCEL_LOAD_CONTROL_EVENT_CB_ID"));
        case 0x0042:
            return mp_obj_new_str("ESP_ZB_CORE_DRLC_CANCEL_ALL_LOAD_CONTROL_EVENTS_CB_ID", strlen("ESP_ZB_CORE_DRLC_CANCEL_ALL_LOAD_CONTROL_EVENTS_CB_ID"));
        case 0x0043:
            return mp_obj_new_str("ESP_ZB_CORE_DRLC_REPORT_EVENT_STATUS_CB_ID", strlen("ESP_ZB_CORE_DRLC_REPORT_EVENT_STATUS_CB_ID"));
        case 0x0044:
            return mp_obj_new_str("ESP_ZB_CORE_DRLC_GET_SCHEDULED_EVENTS_CB_ID", strlen("ESP_ZB_CORE_DRLC_GET_SCHEDULED_EVENTS_CB_ID"));
        case 0x1000:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_READ_ATTR_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_READ_ATTR_RESP_CB_ID"));
        case 0x1001:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_WRITE_ATTR_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_WRITE_ATTR_RESP_CB_ID"));
        case 0x1002:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_REPORT_CONFIG_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_REPORT_CONFIG_RESP_CB_ID"));
        case 0x1003:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_READ_REPORT_CFG_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_READ_REPORT_CFG_RESP_CB_ID"));
        case 0x1004:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_DISC_ATTR_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_DISC_ATTR_RESP_CB_ID"));
        case 0x1005:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_DEFAULT_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_DEFAULT_RESP_CB_ID"));
        case 0x1010:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_OPERATE_GROUP_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_OPERATE_GROUP_RESP_CB_ID"));
        case 0x1011:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_VIEW_GROUP_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_VIEW_GROUP_RESP_CB_ID"));
        case 0x1012:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_GET_GROUP_MEMBERSHIP_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_GET_GROUP_MEMBERSHIP_RESP_CB_ID"));
        case 0x1020:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_OPERATE_SCENE_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_OPERATE_SCENE_RESP_CB_ID"));
        case 0x1021:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_VIEW_SCENE_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_VIEW_SCENE_RESP_CB_ID"));
        case 0x1022:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_GET_SCENE_MEMBERSHIP_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_GET_SCENE_MEMBERSHIP_RESP_CB_ID"));
        case 0x1030:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_IAS_ZONE_ZONE_ENROLL_REQUEST_ID", strlen("ESP_ZB_CORE_CMD_IAS_ZONE_ZONE_ENROLL_REQUEST_ID"));
        case 0x1031:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_IAS_ZONE_ZONE_STATUS_CHANGE_NOT_ID", strlen("ESP_ZB_CORE_CMD_IAS_ZONE_ZONE_STATUS_CHANGE_NOT_ID"));
        case 0x1040:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_CUSTOM_CLUSTER_REQ_CB_ID", strlen("ESP_ZB_CORE_CMD_CUSTOM_CLUSTER_REQ_CB_ID"));
        case 0x1041:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_CUSTOM_CLUSTER_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_CUSTOM_CLUSTER_RESP_CB_ID"));
        case 0x1050:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_PRIVILEGE_COMMAND_REQ_CB_ID", strlen("ESP_ZB_CORE_CMD_PRIVILEGE_COMMAND_REQ_CB_ID"));
        case 0x1051:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_PRIVILEGE_COMMAND_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_PRIVILEGE_COMMAND_RESP_CB_ID"));
        case 0x1060:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_TOUCHLINK_GET_GROUP_ID_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_TOUCHLINK_GET_GROUP_ID_RESP_CB_ID"));
        case 0x1061:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_TOUCHLINK_GET_ENDPOINT_LIST_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_TOUCHLINK_GET_ENDPOINT_LIST_RESP_CB_ID"));
        case 0x1070:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_THERMOSTAT_GET_WEEKLY_SCHEDULE_RESP_CB_ID", strlen("ESP_ZB_CORE_CMD_THERMOSTAT_GET_WEEKLY_SCHEDULE_RESP_CB_ID"));
        case 0x1F00:
            return mp_obj_new_str("ESP_ZB_CORE_CMD_GREEN_POWER_RECV_CB_ID", strlen("ESP_ZB_CORE_CMD_GREEN_POWER_RECV_CB_ID"));
        case 0x2000:
            return mp_obj_new_str("ESP_ZB_CORE_REPORT_ATTR_CB_ID", strlen("ESP_ZB_CORE_REPORT_ATTR_CB_ID"));
        default:
            return mp_obj_new_str("UNKNOWN", 7);
    }
}
static MP_DEFINE_CONST_FUN_OBJ_1(mod_zigbee_actioncallback_get_type_obj, mod_zigbee_actioncallback_get_type);

// size method implementation  
mp_obj_t mod_zigbee_actioncallback_size(mp_obj_t value_in) {
    mp_int_t value = mp_obj_get_int(value_in);
    
    // Return size based on enum type
    // For other enum types, return size based on value range
    if (value <= 0xFF) {
        return MP_OBJ_NEW_SMALL_INT(1);
    } else if (value <= 0xFFFF) {
        return MP_OBJ_NEW_SMALL_INT(2);
    } else {
        return MP_OBJ_NEW_SMALL_INT(4);
    }
}
static MP_DEFINE_CONST_FUN_OBJ_1(mod_zigbee_actioncallback_size_obj, mod_zigbee_actioncallback_size);

// Module dictionary - functions and constants directly accessible
static const mp_rom_map_elem_t mp_module_ZCL_ACTION_CALLBACK_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_ZCL_ACTION_CALLBACK) },
    
    // Module-level functions (not class methods!)
    { MP_ROM_QSTR(MP_QSTR_get_type), MP_ROM_PTR(&mod_zigbee_actioncallback_get_type_obj) },
    { MP_ROM_QSTR(MP_QSTR_size), MP_ROM_PTR(&mod_zigbee_actioncallback_size_obj) },
    
    // Constants directly in module
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_SET_ATTR_VALUE_CB_ID), MP_ROM_INT(0x0000) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_SCENES_STORE_SCENE_CB_ID), MP_ROM_INT(0x0001) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_SCENES_RECALL_SCENE_CB_ID), MP_ROM_INT(0x0002) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ZONE_ENROLL_RESPONSE_VALUE_CB_ID), MP_ROM_INT(0x0003) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_OTA_UPGRADE_VALUE_CB_ID), MP_ROM_INT(0x0004) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_OTA_UPGRADE_SRV_STATUS_CB_ID), MP_ROM_INT(0x0005) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_OTA_UPGRADE_SRV_QUERY_IMAGE_CB_ID), MP_ROM_INT(0x0006) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_THERMOSTAT_VALUE_CB_ID), MP_ROM_INT(0x0007) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_METERING_GET_PROFILE_CB_ID), MP_ROM_INT(0x0008) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_METERING_GET_PROFILE_RESP_CB_ID), MP_ROM_INT(0x0009) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_METERING_REQ_FAST_POLL_MODE_CB_ID), MP_ROM_INT(0x000a) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_METERING_REQ_FAST_POLL_MODE_RESP_CB_ID), MP_ROM_INT(0x000b) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_METERING_GET_SNAPSHOT_CB_ID), MP_ROM_INT(0x000c) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_METERING_PUBLISH_SNAPSHOT_CB_ID), MP_ROM_INT(0x000d) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_METERING_GET_SAMPLED_DATA_CB_ID), MP_ROM_INT(0x000e) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_METERING_GET_SAMPLED_DATA_RESP_CB_ID), MP_ROM_INT(0x000f) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_DOOR_LOCK_LOCK_DOOR_CB_ID), MP_ROM_INT(0x0010) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_DOOR_LOCK_LOCK_DOOR_RESP_CB_ID), MP_ROM_INT(0x0011) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IDENTIFY_EFFECT_CB_ID), MP_ROM_INT(0x0012) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_BASIC_RESET_TO_FACTORY_RESET_CB_ID), MP_ROM_INT(0x0013) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_PRICE_GET_CURRENT_PRICE_CB_ID), MP_ROM_INT(0x0014) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_PRICE_GET_SCHEDULED_PRICES_CB_ID), MP_ROM_INT(0x0015) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_PRICE_GET_TIER_LABELS_CB_ID), MP_ROM_INT(0x0016) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_PRICE_PUBLISH_PRICE_CB_ID), MP_ROM_INT(0x0017) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_PRICE_PUBLISH_TIER_LABELS_CB_ID), MP_ROM_INT(0x0018) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_PRICE_PRICE_ACK_CB_ID), MP_ROM_INT(0x0019) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_COMM_RESTART_DEVICE_CB_ID), MP_ROM_INT(0x001a) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_COMM_OPERATE_STARTUP_PARAMS_CB_ID), MP_ROM_INT(0x001b) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_COMM_COMMAND_RESP_CB_ID), MP_ROM_INT(0x001c) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_WD_START_WARNING_CB_ID), MP_ROM_INT(0x001d) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_WD_SQUAWK_CB_ID), MP_ROM_INT(0x001e) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_ARM_CB_ID), MP_ROM_INT(0x001f) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_BYPASS_CB_ID), MP_ROM_INT(0x0020) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_EMERGENCY_CB_ID), MP_ROM_INT(0x0021) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_FIRE_CB_ID), MP_ROM_INT(0x0022) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_PANIC_CB_ID), MP_ROM_INT(0x0023) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_GET_PANEL_STATUS_CB_ID), MP_ROM_INT(0x0024) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_GET_BYPASSED_ZONE_LIST_CB_ID), MP_ROM_INT(0x0025) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_GET_ZONE_STATUS_CB_ID), MP_ROM_INT(0x0026) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_ARM_RESP_CB_ID), MP_ROM_INT(0x0027) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_GET_ZONE_ID_MAP_RESP_CB_ID), MP_ROM_INT(0x0028) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_GET_ZONE_INFO_RESP_CB_ID), MP_ROM_INT(0x0029) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_ZONE_STATUS_CHANGED_CB_ID), MP_ROM_INT(0x002a) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_PANEL_STATUS_CHANGED_CB_ID), MP_ROM_INT(0x002b) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_GET_PANEL_STATUS_RESP_CB_ID), MP_ROM_INT(0x002c) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_SET_BYPASSED_ZONE_LIST_CB_ID), MP_ROM_INT(0x002d) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_BYPASS_RESP_CB_ID), MP_ROM_INT(0x002e) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_IAS_ACE_GET_ZONE_STATUS_RESP_CB_ID), MP_ROM_INT(0x002f) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_WINDOW_COVERING_MOVEMENT_CB_ID), MP_ROM_INT(0x0030) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_OTA_UPGRADE_QUERY_IMAGE_RESP_CB_ID), MP_ROM_INT(0x0031) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_THERMOSTAT_WEEKLY_SCHEDULE_SET_CB_ID), MP_ROM_INT(0x0032) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_DRLC_LOAD_CONTORL_EVENT_CB_ID), MP_ROM_INT(0x0040) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_DRLC_CANCEL_LOAD_CONTROL_EVENT_CB_ID), MP_ROM_INT(0x0041) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_DRLC_CANCEL_ALL_LOAD_CONTROL_EVENTS_CB_ID), MP_ROM_INT(0x0042) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_DRLC_REPORT_EVENT_STATUS_CB_ID), MP_ROM_INT(0x0043) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_DRLC_GET_SCHEDULED_EVENTS_CB_ID), MP_ROM_INT(0x0044) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_READ_ATTR_RESP_CB_ID), MP_ROM_INT(0x1000) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_WRITE_ATTR_RESP_CB_ID), MP_ROM_INT(0x1001) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_REPORT_CONFIG_RESP_CB_ID), MP_ROM_INT(0x1002) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_READ_REPORT_CFG_RESP_CB_ID), MP_ROM_INT(0x1003) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_DISC_ATTR_RESP_CB_ID), MP_ROM_INT(0x1004) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_DEFAULT_RESP_CB_ID), MP_ROM_INT(0x1005) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_OPERATE_GROUP_RESP_CB_ID), MP_ROM_INT(0x1010) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_VIEW_GROUP_RESP_CB_ID), MP_ROM_INT(0x1011) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_GET_GROUP_MEMBERSHIP_RESP_CB_ID), MP_ROM_INT(0x1012) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_OPERATE_SCENE_RESP_CB_ID), MP_ROM_INT(0x1020) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_VIEW_SCENE_RESP_CB_ID), MP_ROM_INT(0x1021) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_GET_SCENE_MEMBERSHIP_RESP_CB_ID), MP_ROM_INT(0x1022) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_IAS_ZONE_ZONE_ENROLL_REQUEST_ID), MP_ROM_INT(0x1030) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_IAS_ZONE_ZONE_STATUS_CHANGE_NOT_ID), MP_ROM_INT(0x1031) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_CUSTOM_CLUSTER_REQ_CB_ID), MP_ROM_INT(0x1040) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_CUSTOM_CLUSTER_RESP_CB_ID), MP_ROM_INT(0x1041) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_PRIVILEGE_COMMAND_REQ_CB_ID), MP_ROM_INT(0x1050) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_PRIVILEGE_COMMAND_RESP_CB_ID), MP_ROM_INT(0x1051) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_TOUCHLINK_GET_GROUP_ID_RESP_CB_ID), MP_ROM_INT(0x1060) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_TOUCHLINK_GET_ENDPOINT_LIST_RESP_CB_ID), MP_ROM_INT(0x1061) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_THERMOSTAT_GET_WEEKLY_SCHEDULE_RESP_CB_ID), MP_ROM_INT(0x1070) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_CMD_GREEN_POWER_RECV_CB_ID), MP_ROM_INT(0x1F00) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_CORE_REPORT_ATTR_CB_ID), MP_ROM_INT(0x2000) },
};
static MP_DEFINE_CONST_DICT(mp_module_ZCL_ACTION_CALLBACK_globals, mp_module_ZCL_ACTION_CALLBACK_globals_table);

// Module definition
const mp_obj_module_t mp_module_ZCL_ACTION_CALLBACK = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t*)&mp_module_ZCL_ACTION_CALLBACK_globals,
};

// Auto-register the module with MicroPython
MP_REGISTER_MODULE(MP_QSTR_ZCL_ACTION_CALLBACK, mp_module_ZCL_ACTION_CALLBACK);
