/*
 * ZigBee Cluster Library Attribute Types
 * Based on esp_zb_zcl_attr_type_t enum type
 * Generated by generate_separate_modules.py on 2025-05-25 11:05:08
 */

#ifndef MICROPYTHON_ZCL_ATTR_TYPE_H
#define MICROPYTHON_ZCL_ATTR_TYPE_H

#include "py/runtime.h"
#include "py/obj.h"

// Module registration
extern const mp_obj_module_t mp_module_ZCL_ATTR_TYPE;

// Function declarations - module level functions
mp_obj_t mod_zigbee_attrtype_get_type(mp_obj_t value_in);
mp_obj_t mod_zigbee_attrtype_size(mp_obj_t value_in);

#endif // MICROPYTHON_ZCL_ATTR_TYPE_H