/*
 * ZigBee Cluster Library Cluster IDs
 * Based on esp_zb_zcl_cluster_id_t enum type
 * Generated by generate_separate_modules.py on 2025-05-25 11:05:08
 */

#include "py/runtime.h"
#include "py/obj.h"
#include "py/objstr.h"
#include <string.h>
#include "ZCL_CLUSTER.h"

// Module-level function implementations - NO INTERMEDIATE CLASS
// get_type method implementation
mp_obj_t mod_zigbee_cluster_get_type(mp_obj_t value_in) {
    mp_int_t value = mp_obj_get_int(value_in);
    
    // Return type information based on value
    switch (value) {
        case 0x0000:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_BASIC", strlen("ESP_ZB_ZCL_CLUSTER_ID_BASIC"));
        case 0x0001:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_POWER_CONFIG", strlen("ESP_ZB_ZCL_CLUSTER_ID_POWER_CONFIG"));
        case 0x0002:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_DEVICE_TEMP_CONFIG", strlen("ESP_ZB_ZCL_CLUSTER_ID_DEVICE_TEMP_CONFIG"));
        case 0x0003:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_IDENTIFY", strlen("ESP_ZB_ZCL_CLUSTER_ID_IDENTIFY"));
        case 0x0004:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_GROUPS", strlen("ESP_ZB_ZCL_CLUSTER_ID_GROUPS"));
        case 0x0005:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_SCENES", strlen("ESP_ZB_ZCL_CLUSTER_ID_SCENES"));
        case 0x0006:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_ON_OFF", strlen("ESP_ZB_ZCL_CLUSTER_ID_ON_OFF"));
        case 0x0007:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_ON_OFF_SWITCH_CONFIG", strlen("ESP_ZB_ZCL_CLUSTER_ID_ON_OFF_SWITCH_CONFIG"));
        case 0x0008:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_LEVEL_CONTROL", strlen("ESP_ZB_ZCL_CLUSTER_ID_LEVEL_CONTROL"));
        case 0x0009:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_ALARMS", strlen("ESP_ZB_ZCL_CLUSTER_ID_ALARMS"));
        case 0x000a:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_TIME", strlen("ESP_ZB_ZCL_CLUSTER_ID_TIME"));
        case 0x000b:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_RSSI_LOCATION", strlen("ESP_ZB_ZCL_CLUSTER_ID_RSSI_LOCATION"));
        case 0x000c:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_ANALOG_INPUT", strlen("ESP_ZB_ZCL_CLUSTER_ID_ANALOG_INPUT"));
        case 0x000d:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_ANALOG_OUTPUT", strlen("ESP_ZB_ZCL_CLUSTER_ID_ANALOG_OUTPUT"));
        case 0x000e:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_ANALOG_VALUE", strlen("ESP_ZB_ZCL_CLUSTER_ID_ANALOG_VALUE"));
        case 0x000f:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_BINARY_INPUT", strlen("ESP_ZB_ZCL_CLUSTER_ID_BINARY_INPUT"));
        case 0x0010:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_BINARY_OUTPUT", strlen("ESP_ZB_ZCL_CLUSTER_ID_BINARY_OUTPUT"));
        case 0x0011:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_BINARY_VALUE", strlen("ESP_ZB_ZCL_CLUSTER_ID_BINARY_VALUE"));
        case 0x0012:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_MULTI_INPUT", strlen("ESP_ZB_ZCL_CLUSTER_ID_MULTI_INPUT"));
        case 0x0013:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_MULTI_OUTPUT", strlen("ESP_ZB_ZCL_CLUSTER_ID_MULTI_OUTPUT"));
        case 0x0014:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_MULTI_VALUE", strlen("ESP_ZB_ZCL_CLUSTER_ID_MULTI_VALUE"));
        case 0x0015:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_COMMISSIONING", strlen("ESP_ZB_ZCL_CLUSTER_ID_COMMISSIONING"));
        case 0x0019:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_OTA_UPGRADE", strlen("ESP_ZB_ZCL_CLUSTER_ID_OTA_UPGRADE"));
        case 0x0020:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_POLL_CONTROL", strlen("ESP_ZB_ZCL_CLUSTER_ID_POLL_CONTROL"));
        case 0x0021:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_GREEN_POWER", strlen("ESP_ZB_ZCL_CLUSTER_ID_GREEN_POWER"));
        case 0x0025:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_KEEP_ALIVE", strlen("ESP_ZB_ZCL_CLUSTER_ID_KEEP_ALIVE"));
        case 0x0100:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_SHADE_CONFIG", strlen("ESP_ZB_ZCL_CLUSTER_ID_SHADE_CONFIG"));
        case 0x0101:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_DOOR_LOCK", strlen("ESP_ZB_ZCL_CLUSTER_ID_DOOR_LOCK"));
        case 0x0102:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_WINDOW_COVERING", strlen("ESP_ZB_ZCL_CLUSTER_ID_WINDOW_COVERING"));
        case 0x0200:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_PUMP_CONFIG_CONTROL", strlen("ESP_ZB_ZCL_CLUSTER_ID_PUMP_CONFIG_CONTROL"));
        case 0x0201:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_THERMOSTAT", strlen("ESP_ZB_ZCL_CLUSTER_ID_THERMOSTAT"));
        case 0x0202:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_FAN_CONTROL", strlen("ESP_ZB_ZCL_CLUSTER_ID_FAN_CONTROL"));
        case 0x0203:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_DEHUMIDIFICATION_CONTROL", strlen("ESP_ZB_ZCL_CLUSTER_ID_DEHUMIDIFICATION_CONTROL"));
        case 0x0204:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_THERMOSTAT_UI_CONFIG", strlen("ESP_ZB_ZCL_CLUSTER_ID_THERMOSTAT_UI_CONFIG"));
        case 0x0300:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_COLOR_CONTROL", strlen("ESP_ZB_ZCL_CLUSTER_ID_COLOR_CONTROL"));
        case 0x0301:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_BALLAST_CONFIG", strlen("ESP_ZB_ZCL_CLUSTER_ID_BALLAST_CONFIG"));
        case 0x0400:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_ILLUMINANCE_MEASUREMENT", strlen("ESP_ZB_ZCL_CLUSTER_ID_ILLUMINANCE_MEASUREMENT"));
        case 0x0402:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_TEMP_MEASUREMENT", strlen("ESP_ZB_ZCL_CLUSTER_ID_TEMP_MEASUREMENT"));
        case 0x0403:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_PRESSURE_MEASUREMENT", strlen("ESP_ZB_ZCL_CLUSTER_ID_PRESSURE_MEASUREMENT"));
        case 0x0404:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_FLOW_MEASUREMENT", strlen("ESP_ZB_ZCL_CLUSTER_ID_FLOW_MEASUREMENT"));
        case 0x0405:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_REL_HUMIDITY_MEASUREMENT", strlen("ESP_ZB_ZCL_CLUSTER_ID_REL_HUMIDITY_MEASUREMENT"));
        case 0x0406:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_OCCUPANCY_SENSING", strlen("ESP_ZB_ZCL_CLUSTER_ID_OCCUPANCY_SENSING"));
        case 0x0409:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_PH_MEASUREMENT", strlen("ESP_ZB_ZCL_CLUSTER_ID_PH_MEASUREMENT"));
        case 0x040a:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_EC_MEASUREMENT", strlen("ESP_ZB_ZCL_CLUSTER_ID_EC_MEASUREMENT"));
        case 0x040b:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_WIND_SPEED_MEASUREMENT", strlen("ESP_ZB_ZCL_CLUSTER_ID_WIND_SPEED_MEASUREMENT"));
        case 0x040d:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_CARBON_DIOXIDE_MEASUREMENT", strlen("ESP_ZB_ZCL_CLUSTER_ID_CARBON_DIOXIDE_MEASUREMENT"));
        case 0x042a:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_PM2_5_MEASUREMENT", strlen("ESP_ZB_ZCL_CLUSTER_ID_PM2_5_MEASUREMENT"));
        case 0x0500:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_IAS_ZONE", strlen("ESP_ZB_ZCL_CLUSTER_ID_IAS_ZONE"));
        case 0x0501:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_IAS_ACE", strlen("ESP_ZB_ZCL_CLUSTER_ID_IAS_ACE"));
        case 0x0502:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_IAS_WD", strlen("ESP_ZB_ZCL_CLUSTER_ID_IAS_WD"));
        case 0x0700:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_PRICE", strlen("ESP_ZB_ZCL_CLUSTER_ID_PRICE"));
        case 0x0701:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_DRLC", strlen("ESP_ZB_ZCL_CLUSTER_ID_DRLC"));
        case 0x0702:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_METERING", strlen("ESP_ZB_ZCL_CLUSTER_ID_METERING"));
        case 0x0b01:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_METER_IDENTIFICATION", strlen("ESP_ZB_ZCL_CLUSTER_ID_METER_IDENTIFICATION"));
        case 0x0b04:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_ELECTRICAL_MEASUREMENT", strlen("ESP_ZB_ZCL_CLUSTER_ID_ELECTRICAL_MEASUREMENT"));
        case 0x0b05:
            return mp_obj_new_str("ESP_ZB_ZCL_CLUSTER_ID_DIAGNOSTICS", strlen("ESP_ZB_ZCL_CLUSTER_ID_DIAGNOSTICS"));
        default:
            return mp_obj_new_str("UNKNOWN", 7);
    }
}
static MP_DEFINE_CONST_FUN_OBJ_1(mod_zigbee_cluster_get_type_obj, mod_zigbee_cluster_get_type);

// size method implementation  
mp_obj_t mod_zigbee_cluster_size(mp_obj_t value_in) {
    (void)value_in; // Mark value_in as unused for specific enum types
    
    // Return size based on enum type
    // Device/Cluster/Profile IDs are typically 16-bit (2 bytes)
    return MP_OBJ_NEW_SMALL_INT(2);
}
static MP_DEFINE_CONST_FUN_OBJ_1(mod_zigbee_cluster_size_obj, mod_zigbee_cluster_size);

// Module dictionary - functions and constants directly accessible
static const mp_rom_map_elem_t mp_module_ZCL_CLUSTER_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_ZCL_CLUSTER) },
    
    // Module-level functions (not class methods!)
    { MP_ROM_QSTR(MP_QSTR_get_type), MP_ROM_PTR(&mod_zigbee_cluster_get_type_obj) },
    { MP_ROM_QSTR(MP_QSTR_size), MP_ROM_PTR(&mod_zigbee_cluster_size_obj) },
    
    // Constants directly in module
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_BASIC), MP_ROM_INT(0x0000) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_POWER_CONFIG), MP_ROM_INT(0x0001) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_DEVICE_TEMP_CONFIG), MP_ROM_INT(0x0002) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_IDENTIFY), MP_ROM_INT(0x0003) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_GROUPS), MP_ROM_INT(0x0004) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_SCENES), MP_ROM_INT(0x0005) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_ON_OFF), MP_ROM_INT(0x0006) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_ON_OFF_SWITCH_CONFIG), MP_ROM_INT(0x0007) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_LEVEL_CONTROL), MP_ROM_INT(0x0008) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_ALARMS), MP_ROM_INT(0x0009) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_TIME), MP_ROM_INT(0x000a) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_RSSI_LOCATION), MP_ROM_INT(0x000b) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_ANALOG_INPUT), MP_ROM_INT(0x000c) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_ANALOG_OUTPUT), MP_ROM_INT(0x000d) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_ANALOG_VALUE), MP_ROM_INT(0x000e) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_BINARY_INPUT), MP_ROM_INT(0x000f) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_BINARY_OUTPUT), MP_ROM_INT(0x0010) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_BINARY_VALUE), MP_ROM_INT(0x0011) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_MULTI_INPUT), MP_ROM_INT(0x0012) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_MULTI_OUTPUT), MP_ROM_INT(0x0013) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_MULTI_VALUE), MP_ROM_INT(0x0014) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_COMMISSIONING), MP_ROM_INT(0x0015) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_OTA_UPGRADE), MP_ROM_INT(0x0019) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_POLL_CONTROL), MP_ROM_INT(0x0020) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_GREEN_POWER), MP_ROM_INT(0x0021) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_KEEP_ALIVE), MP_ROM_INT(0x0025) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_SHADE_CONFIG), MP_ROM_INT(0x0100) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_DOOR_LOCK), MP_ROM_INT(0x0101) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_WINDOW_COVERING), MP_ROM_INT(0x0102) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_PUMP_CONFIG_CONTROL), MP_ROM_INT(0x0200) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_THERMOSTAT), MP_ROM_INT(0x0201) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_FAN_CONTROL), MP_ROM_INT(0x0202) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_DEHUMIDIFICATION_CONTROL), MP_ROM_INT(0x0203) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_THERMOSTAT_UI_CONFIG), MP_ROM_INT(0x0204) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_COLOR_CONTROL), MP_ROM_INT(0x0300) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_BALLAST_CONFIG), MP_ROM_INT(0x0301) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_ILLUMINANCE_MEASUREMENT), MP_ROM_INT(0x0400) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_TEMP_MEASUREMENT), MP_ROM_INT(0x0402) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_PRESSURE_MEASUREMENT), MP_ROM_INT(0x0403) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_FLOW_MEASUREMENT), MP_ROM_INT(0x0404) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_REL_HUMIDITY_MEASUREMENT), MP_ROM_INT(0x0405) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_OCCUPANCY_SENSING), MP_ROM_INT(0x0406) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_PH_MEASUREMENT), MP_ROM_INT(0x0409) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_EC_MEASUREMENT), MP_ROM_INT(0x040a) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_WIND_SPEED_MEASUREMENT), MP_ROM_INT(0x040b) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_CARBON_DIOXIDE_MEASUREMENT), MP_ROM_INT(0x040d) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_PM2_5_MEASUREMENT), MP_ROM_INT(0x042a) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_IAS_ZONE), MP_ROM_INT(0x0500) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_IAS_ACE), MP_ROM_INT(0x0501) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_IAS_WD), MP_ROM_INT(0x0502) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_PRICE), MP_ROM_INT(0x0700) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_DRLC), MP_ROM_INT(0x0701) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_METERING), MP_ROM_INT(0x0702) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_METER_IDENTIFICATION), MP_ROM_INT(0x0b01) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_ELECTRICAL_MEASUREMENT), MP_ROM_INT(0x0b04) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_CLUSTER_ID_DIAGNOSTICS), MP_ROM_INT(0x0b05) },
};
static MP_DEFINE_CONST_DICT(mp_module_ZCL_CLUSTER_globals, mp_module_ZCL_CLUSTER_globals_table);

// Module definition
const mp_obj_module_t mp_module_ZCL_CLUSTER = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t*)&mp_module_ZCL_CLUSTER_globals,
};

// Auto-register the module with MicroPython
MP_REGISTER_MODULE(MP_QSTR_ZCL_CLUSTER, mp_module_ZCL_CLUSTER);
