/*
 * ZigBee Application Framework Profile IDs
 * Based on esp_zb_af_profile_id_t enum type
 * Generated by generate_separate_modules.py on 2025-05-25 11:05:08
 */

#include "py/runtime.h"
#include "py/obj.h"
#include "py/objstr.h"
#include <string.h>
#include "ZCL_PROFILE.h"

// Module-level function implementations - NO INTERMEDIATE CLASS
// get_type method implementation
mp_obj_t mod_zigbee_profile_get_type(mp_obj_t value_in) {
    mp_int_t value = mp_obj_get_int(value_in);
    
    // Return type information based on value
    switch (value) {
        case 0x0104:
            return mp_obj_new_str("ESP_ZB_AF_HA_PROFILE_ID", strlen("ESP_ZB_AF_HA_PROFILE_ID"));
        case 0x0109:
            return mp_obj_new_str("ESP_ZB_AF_SE_PROFILE_ID", strlen("ESP_ZB_AF_SE_PROFILE_ID"));
        case 0xA1E0:
            return mp_obj_new_str("ESP_ZB_AF_GP_PROFILE_ID", strlen("ESP_ZB_AF_GP_PROFILE_ID"));
        case 0xC05E:
            return mp_obj_new_str("ESP_ZB_AF_ZLL_PROFILE_ID", strlen("ESP_ZB_AF_ZLL_PROFILE_ID"));
        default:
            return mp_obj_new_str("UNKNOWN", 7);
    }
}
static MP_DEFINE_CONST_FUN_OBJ_1(mod_zigbee_profile_get_type_obj, mod_zigbee_profile_get_type);

// size method implementation  
mp_obj_t mod_zigbee_profile_size(mp_obj_t value_in) {
    (void)value_in; // Mark value_in as unused for specific enum types
    
    // Return size based on enum type
    // Device/Cluster/Profile IDs are typically 16-bit (2 bytes)
    return MP_OBJ_NEW_SMALL_INT(2);
}
static MP_DEFINE_CONST_FUN_OBJ_1(mod_zigbee_profile_size_obj, mod_zigbee_profile_size);

// Module dictionary - functions and constants directly accessible
static const mp_rom_map_elem_t mp_module_ZCL_PROFILE_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_ZCL_PROFILE) },
    
    // Module-level functions (not class methods!)
    { MP_ROM_QSTR(MP_QSTR_get_type), MP_ROM_PTR(&mod_zigbee_profile_get_type_obj) },
    { MP_ROM_QSTR(MP_QSTR_size), MP_ROM_PTR(&mod_zigbee_profile_size_obj) },
    
    // Constants directly in module
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_AF_HA_PROFILE_ID), MP_ROM_INT(0x0104) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_AF_SE_PROFILE_ID), MP_ROM_INT(0x0109) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_AF_GP_PROFILE_ID), MP_ROM_INT(0xA1E0) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_AF_ZLL_PROFILE_ID), MP_ROM_INT(0xC05E) },
};
static MP_DEFINE_CONST_DICT(mp_module_ZCL_PROFILE_globals, mp_module_ZCL_PROFILE_globals_table);

// Module definition
const mp_obj_module_t mp_module_ZCL_PROFILE = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t*)&mp_module_ZCL_PROFILE_globals,
};

// Auto-register the module with MicroPython
MP_REGISTER_MODULE(MP_QSTR_ZCL_PROFILE, mp_module_ZCL_PROFILE);
