/*
 * ZigBee Cluster Library Status Codes
 * Based on esp_zb_zcl_status_t enum type
 * Generated by generate_separate_modules.py on 2025-05-25 11:05:08
 */

#include "py/runtime.h"
#include "py/obj.h"
#include "py/objstr.h"
#include <string.h>
#include "ZCL_STATUS.h"

// Module-level function implementations - NO INTERMEDIATE CLASS
// get_type method implementation
mp_obj_t mod_zigbee_status_get_type(mp_obj_t value_in) {
    mp_int_t value = mp_obj_get_int(value_in);
    
    // Return type information based on value
    switch (value) {
        case 0x00:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_SUCCESS", strlen("ESP_ZB_ZCL_STATUS_SUCCESS"));
        case 0x01:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_FAIL", strlen("ESP_ZB_ZCL_STATUS_FAIL"));
        case 0x7E:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_NOT_AUTHORIZED", strlen("ESP_ZB_ZCL_STATUS_NOT_AUTHORIZED"));
        case 0x80:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_MALFORMED_CMD", strlen("ESP_ZB_ZCL_STATUS_MALFORMED_CMD"));
        case 0x81:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_UNSUP_CLUST_CMD", strlen("ESP_ZB_ZCL_STATUS_UNSUP_CLUST_CMD"));
        case 0x82:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_UNSUP_GEN_CMD", strlen("ESP_ZB_ZCL_STATUS_UNSUP_GEN_CMD"));
        case 0x83:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_UNSUP_MANUF_CLUST_CMD", strlen("ESP_ZB_ZCL_STATUS_UNSUP_MANUF_CLUST_CMD"));
        case 0x84:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_UNSUP_MANUF_GEN_CMD", strlen("ESP_ZB_ZCL_STATUS_UNSUP_MANUF_GEN_CMD"));
        case 0x85:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_INVALID_FIELD", strlen("ESP_ZB_ZCL_STATUS_INVALID_FIELD"));
        case 0x86:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_UNSUP_ATTRIB", strlen("ESP_ZB_ZCL_STATUS_UNSUP_ATTRIB"));
        case 0x87:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_INVALID_VALUE", strlen("ESP_ZB_ZCL_STATUS_INVALID_VALUE"));
        case 0x88:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_READ_ONLY", strlen("ESP_ZB_ZCL_STATUS_READ_ONLY"));
        case 0x89:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_INSUFF_SPACE", strlen("ESP_ZB_ZCL_STATUS_INSUFF_SPACE"));
        case 0x8a:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_DUPE_EXISTS", strlen("ESP_ZB_ZCL_STATUS_DUPE_EXISTS"));
        case 0x8b:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_NOT_FOUND", strlen("ESP_ZB_ZCL_STATUS_NOT_FOUND"));
        case 0x8c:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_UNREPORTABLE_ATTRIB", strlen("ESP_ZB_ZCL_STATUS_UNREPORTABLE_ATTRIB"));
        case 0x8d:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_INVALID_TYPE", strlen("ESP_ZB_ZCL_STATUS_INVALID_TYPE"));
        case 0x8f:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_WRITE_ONLY", strlen("ESP_ZB_ZCL_STATUS_WRITE_ONLY"));
        case 0x92:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_INCONSISTENT", strlen("ESP_ZB_ZCL_STATUS_INCONSISTENT"));
        case 0x93:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_ACTION_DENIED", strlen("ESP_ZB_ZCL_STATUS_ACTION_DENIED"));
        case 0x94:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_TIMEOUT", strlen("ESP_ZB_ZCL_STATUS_TIMEOUT"));
        case 0x95:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_ABORT", strlen("ESP_ZB_ZCL_STATUS_ABORT"));
        case 0x96:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_INVALID_IMAGE", strlen("ESP_ZB_ZCL_STATUS_INVALID_IMAGE"));
        case 0x97:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_WAIT_FOR_DATA", strlen("ESP_ZB_ZCL_STATUS_WAIT_FOR_DATA"));
        case 0x98:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_NO_IMAGE_AVAILABLE", strlen("ESP_ZB_ZCL_STATUS_NO_IMAGE_AVAILABLE"));
        case 0x99:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_REQUIRE_MORE_IMAGE", strlen("ESP_ZB_ZCL_STATUS_REQUIRE_MORE_IMAGE"));
        case 0x9A:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_NOTIFICATION_PENDING", strlen("ESP_ZB_ZCL_STATUS_NOTIFICATION_PENDING"));
        case 0xc0:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_HW_FAIL", strlen("ESP_ZB_ZCL_STATUS_HW_FAIL"));
        case 0xc1:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_SW_FAIL", strlen("ESP_ZB_ZCL_STATUS_SW_FAIL"));
        case 0xc2:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_CALIB_ERR", strlen("ESP_ZB_ZCL_STATUS_CALIB_ERR"));
        case 0xc3:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_UNSUP_CLUST", strlen("ESP_ZB_ZCL_STATUS_UNSUP_CLUST"));
        case 0xc4:
            return mp_obj_new_str("ESP_ZB_ZCL_STATUS_LIMIT_REACHED", strlen("ESP_ZB_ZCL_STATUS_LIMIT_REACHED"));
        default:
            return mp_obj_new_str("UNKNOWN", 7);
    }
}
static MP_DEFINE_CONST_FUN_OBJ_1(mod_zigbee_status_get_type_obj, mod_zigbee_status_get_type);

// size method implementation  
mp_obj_t mod_zigbee_status_size(mp_obj_t value_in) {
    (void)value_in; // Mark value_in as unused for specific enum types
    
    // Return size based on enum type
    // Status codes are typically 8-bit (1 byte)
    return MP_OBJ_NEW_SMALL_INT(1);
}
static MP_DEFINE_CONST_FUN_OBJ_1(mod_zigbee_status_size_obj, mod_zigbee_status_size);

// Module dictionary - functions and constants directly accessible
static const mp_rom_map_elem_t mp_module_ZCL_STATUS_globals_table[] = {
    { MP_ROM_QSTR(MP_QSTR___name__), MP_ROM_QSTR(MP_QSTR_ZCL_STATUS) },
    
    // Module-level functions (not class methods!)
    { MP_ROM_QSTR(MP_QSTR_get_type), MP_ROM_PTR(&mod_zigbee_status_get_type_obj) },
    { MP_ROM_QSTR(MP_QSTR_size), MP_ROM_PTR(&mod_zigbee_status_size_obj) },
    
    // Constants directly in module
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_SUCCESS), MP_ROM_INT(0x00) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_FAIL), MP_ROM_INT(0x01) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_NOT_AUTHORIZED), MP_ROM_INT(0x7E) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_MALFORMED_CMD), MP_ROM_INT(0x80) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_UNSUP_CLUST_CMD), MP_ROM_INT(0x81) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_UNSUP_GEN_CMD), MP_ROM_INT(0x82) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_UNSUP_MANUF_CLUST_CMD), MP_ROM_INT(0x83) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_UNSUP_MANUF_GEN_CMD), MP_ROM_INT(0x84) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_INVALID_FIELD), MP_ROM_INT(0x85) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_UNSUP_ATTRIB), MP_ROM_INT(0x86) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_INVALID_VALUE), MP_ROM_INT(0x87) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_READ_ONLY), MP_ROM_INT(0x88) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_INSUFF_SPACE), MP_ROM_INT(0x89) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_DUPE_EXISTS), MP_ROM_INT(0x8a) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_NOT_FOUND), MP_ROM_INT(0x8b) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_UNREPORTABLE_ATTRIB), MP_ROM_INT(0x8c) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_INVALID_TYPE), MP_ROM_INT(0x8d) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_WRITE_ONLY), MP_ROM_INT(0x8f) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_INCONSISTENT), MP_ROM_INT(0x92) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_ACTION_DENIED), MP_ROM_INT(0x93) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_TIMEOUT), MP_ROM_INT(0x94) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_ABORT), MP_ROM_INT(0x95) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_INVALID_IMAGE), MP_ROM_INT(0x96) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_WAIT_FOR_DATA), MP_ROM_INT(0x97) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_NO_IMAGE_AVAILABLE), MP_ROM_INT(0x98) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_REQUIRE_MORE_IMAGE), MP_ROM_INT(0x99) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_NOTIFICATION_PENDING), MP_ROM_INT(0x9A) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_HW_FAIL), MP_ROM_INT(0xc0) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_SW_FAIL), MP_ROM_INT(0xc1) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_CALIB_ERR), MP_ROM_INT(0xc2) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_UNSUP_CLUST), MP_ROM_INT(0xc3) },
    { MP_ROM_QSTR(MP_QSTR_ESP_ZB_ZCL_STATUS_LIMIT_REACHED), MP_ROM_INT(0xc4) },
};
static MP_DEFINE_CONST_DICT(mp_module_ZCL_STATUS_globals, mp_module_ZCL_STATUS_globals_table);

// Module definition
const mp_obj_module_t mp_module_ZCL_STATUS = {
    .base = { &mp_type_module },
    .globals = (mp_obj_dict_t*)&mp_module_ZCL_STATUS_globals,
};

// Auto-register the module with MicroPython
MP_REGISTER_MODULE(MP_QSTR_ZCL_STATUS, mp_module_ZCL_STATUS);
